## 分布式事务配置
#seata:
#  tx-service-group: mall-product-seata-service-group
#  enable-auto-data-source-proxy: true
#  registry:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848
#      namespace: 81bd7db6-0d67-4789-9d9d-9ac25bf37f43
#      group: SEATA_GROUP
#  config:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848
#      namespace: 81bd7db6-0d67-4789-9d9d-9ac25bf37f43
#      group: SEATA_GROUP


